Router.route('/webhooks/trello', { where: 'server' })
  .get(function () {
    // GET /webhooks/stripe
  })
  .post(function () {
    this.response.statusCode = 403;
    var reason = 'webhook validation failed, either this webhook was not generated by this server or something went wrong';
    if (Meteor.call('didTrelloWebhookValidate', this.request)) {
      this.response.statusCode = 200;
      reason = '';
    }

    this.response.end(reason);
  })
  .put(function () {
    // PUT /webhooks/stripe
  })
